server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apisample?useUnicode=yes&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin
    username: dbuser
    password: lineschool
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: set names utf8mb4